ALL_PLACES_TYPES = [
 'accounting',                'fire_station',             'pharmacy',
 'airport',                   'florist',                  'physiotherapist',
 'amusement_park',            'funeral_home',             'plumber',
 'aquarium',                  'furniture_store',          'police',
 'art_gallery',               'gas_station',              'post_office',
 'atm',                       'gym',                      'primary_school',
 'bakery',                    'hair_care',                'real_estate_agency',
 'bank',                      'hardware_store',           'restaurant',
 'bar',                       'hindu_temple',             'roofing_contractor',
 'beauty_salon',              'home_goods_store',         'rv_park',
 'bicycle_store',             'hospital',                 'school',
 'book_store',                'insurance_agency',         'secondary_school',
 'bowling_alley',             'jewelry_store',            'shoe_store',
 'bus_station',               'laundry',                  'shopping_mall',
 'cafe',                      'lawyer',                   'spa',
 'campground',                'library',                  'stadium',
 'car_dealer',                'light_rail_station',       'storage',
 'car_rental',                'liquor_store',             'store',
 'car_repair',                'local_government_office',  'subway_station',
 'car_wash',                  'locksmith',                'supermarket',
 'casino',                    'lodging',                  'synagogue',
 'cemetery',                  'meal_delivery',            'taxi_stand',    
 'church',                    'meal_takeaway',            'tourist_attraction',
 'city_hall',                 'mosque',                   'train_station',
 'clothing_store',            'movie_rental',             'transit_station',
 'convenience_store',         'movie_theater',            'travel_agency',
 'courthouse',                'moving_company',           'university',
 'dentist',                   'museum',                   'veterinary_care',
 'department_store',          'night_club',               'zoo',
 'doctor',                    'painter',
 'drugstore',                 'park',
 'electrician',               'parking',
 'electronics_store',         'parking',
 'embassy',                   'pet_store',
]

ALL_PLACES_TYPES_FILTER = [
    'pharmacy',
    'funeral_home',           
    'furniture_store',          
    'police',
    'gas_station',
    'atm',
    'gym',                      
    'hair_care',                
    'bank',                      
    'hardware_store',           
    'restaurant',
    'bar',                       
    'beauty_salon',                   
    'rv_park',
    'bicycle_store',             
    'hospital',                 
    'book_store',           
    'jewelry_store',            
    'shoe_store',
    'shopping_mall',
    'cafe',                               
    'spa',
    'library',                 
    'car_dealer',                     
    'liquor_store',             
    'store',
    'car_repair',                 
    'supermarket',
    'casino',                    
    'lodging',                 
    'meal_delivery',            
    'church',                    
    'clothing_store',                       
    'convenience_store',         
    'courthouse',                      
    'dentist',                                 
    'veterinary_care',
    'night_club',             
    'doctor',
    'park',
    'parking',
    'electronics store',    
    'pet_store',
]

PRINCIPALS_PLACES = [
    'pharmacy',
    'furniture_store',          
    'police',
    'gas_station',
    'atm',
    'gym',                      
    'bank',                      
    'restaurant',
    'bar',                       
    'rv_park', 
    'jewelry_store',            
    'shoe_store',
    'shopping_mall',
    'cafe',                               
    'liquor_store',             
    'store',
    'supermarket',
    'casino',                    
    'n',                       
    'church',                    
    'clothing_store',                                           
    'veterinary_care',      
    'night_club',             
    'doctor',
]